### ISSUE TITLE
[Bug] Duplicate import from Thingiverse

### ISSUE THREAD

**Issue by mechanarchy** [Maker-Management-Platform/agent#126]
Hi, it seems you can import the same Thingiverse project multiple times.

Steps to reproduce:
1. Set up a Thingiverse API key
2. Go to your MMP server, Projects -> Import
3. Enter a Thingiverse URL, eg https://www.thingiverse.com/thing:6527320
4. Click Submit and wait for the toast notification + button to stop showing the spinner
5. Click Submit again and wait for the toast notification
6. Go back to the Projects view, and see the same project is there twice.

Related bugs (I can create separate issues if preferred):
* Assets (eg, images) are shared by both duplicated projects. The projects have unique keys, but the assets don't - so deleting one of the projects breaks the other as the image data on disk is deleted, but not in the database/project view.
* The 'External Link' for thingiverse-imported projects is set to the API view. This prevents the user from easily viewing the external source by clicking the button. Compare:
  * URL used in the import field, as submitted by the user: https://www.thingiverse.com/thing:6527320
  * URL set in the 'External Link' field of the project: https://api.thingiverse.com/things/6527320

**Comment by EduardoOliveira** [comment]
Thanks for the awesome feedback, I'm gonna start working on a fix now.
I was thinking about swapping the / characters by - to avoid the last issue.
As for the duplicate import, I'll try to make it so it redownloads the assets withou errors
