### ISSUE TITLE
stls not being inserted

### ISSUE THREAD

**Issue by C0untZero** [Maker-Management-Platform/agent#59]
I'm running mmp through docker-compose on my rpi5.
I put a bunch of stls in various folders in my mmp library and the projects are not auto created.
When I check out the agent logs I see just the first stl with the message produced png, rendering png,
and then just endless spam of the logs for printer connectivity.

Am I doing something wrong?

**Comment by javijuji** [comment]
I am having the same issue. Library isn't getting scanned.

**Comment by EduardoOliveira** [comment]
Hi
@C0untZero  does it stop on the first model? Does the image get written into the library?

@javijuji Are you also running on a RPI5?

**Comment by C0untZero** [comment]
Hi hi,

Yeah, it does the first image and then nothing happens.

**Comment by EduardoOliveira** [comment]
Hi could you please test this branch https://github.com/Maker-Management-Platform/agent/pkgs/container/agent/168820804?tag=missing-error-handling-for-rendering ? I've made some changes that might solve it

**Comment by C0untZero** [comment]
Same behavior on that branch as well.

**Comment by EduardoOliveira** [comment]
Could you post logs for discovery?

**Comment by C0untZero** [comment]
Not much in the logs
[mmp.txt](https://github.com/Maker-Management-Platform/agent/files/14050394/mmp.txt)

**Comment by EduardoOliveira** [comment]
I'm gonna try to reproduce the issue on an RPI, I will only have access to a RPI4...
I've downloaded a couple of Rumble minies to test... they are pretty detailed... compared to other models I have, Jana takes about 3 times to render... Might the ARM be a bottleneck there?
Whats the CPU load? I would assume you would get 1 core to 100% and drop after the image is rendered, the render finish is not in your logs...
Can you describe the CPU behavior when you boot MMP?

**Comment by C0untZero** [comment]
Yeah, all 4 cores actually get smashed to 100%. I've tried leaving it on like that for a while but no luck.
![image](https://github.com/Maker-Management-Platform/agent/assets/9478173/b69d6178-0b6b-4092-a482-283a94d98c7c)

You can test on the actual stls I'm using, they're available here - https://warcraftrumble.blizzard.com/en-us/collection.
This is the first one on the list which stops everything - https://assets.warcraftrumble.blizzard.com/blueprints/warcraft_rumble_alliance_jainaproudmoore.zip.

**Comment by EduardoOliveira** [comment]
Hi, sorry for the late response...
I went and bought a rpi5 8gb.
I was able to reproduce the problem with some models.
"Normal models" work just fine, a little slower than on my server, but high res models like the ones from Rumble take way too long.

Looking at the library that I'm currently using to render the models, It does a CPU count and uses all the cores to compute the render... Not configurable...
I'll think of something as a workaround while I try to contact the library developer or test with others.

Worst case scenario, rendering detaches from discovery (it should so it doesn't block the whole usage of the app), each model goes into render with a configurable timeout, if it reaches the timeout goes into some kind of blacklist.

**Comment by C0untZero** [comment]
Wow, that's commitment to a project :D Getting an rpi5 just to reproduce a bug.
Thanks man! 

Yeah, I guess it would makes sense to split discovery and rendering, I'd be fine with not having some models on preview as long as I can list them in the library at least.

![2ab8b38b-6575-48c1-8cb4-e04616190582_text](https://github.com/Maker-Management-Platform/agent/assets/9478173/6df18f93-b807-4dc6-9f86-95e7ce00e331)

**Comment by EduardoOliveira** [comment]
![image](https://github.com/Maker-Management-Platform/agent/assets/1675917/6a170503-2d3e-4e9b-930a-bdb4c554a5e1)
Running on an RPI5 8gb :)
I hope to have something you can run soon
