### ISSUE TITLE
Bug - Renaming project throwing "invalid cross-device link" error

### ISSUE THREAD

**Issue by HavocWyrm** [Maker-Management-Platform/agent#63]
Renaming an existing project throws the error in the screenshot below

![image](https://github.com/Maker-Management-Platform/agent/assets/23390583/90cf8c8c-72b0-459a-a9d0-feb86816e7d4)

**Comment by EduardoOliveira** [comment]
Hi, could you please test this image https://github.com/Maker-Management-Platform/agent/pkgs/container/agent/168581841?tag=63-bug-renaming-project-throwing-invalid-cross-device-link-error ?
I do believe it's fixed, but would like some confirmation before merging
