### ISSUE TITLE
Bug - Creating an empty project throws a 400 error

### ISSUE THREAD

**Issue by HavocWyrm** [Maker-Management-Platform/agent#69]
If you create a project via the UI with no assets, the application throws a 400 error

**Comment by Buddinski88** [comment]
Unfortunally i can confirm that. What information are needed to debug that issue?

**Comment by EduardoOliveira** [comment]
At this point, the but is to allow project creation without assets.
Is that a thing that makes sense for you guys? Creating the project without uploading files?
